site_name: ドキュメンテーション戦略
site_url: https://nuitsjp.github.io/mkdocs-mermaid-to-image/
repo_url: https://github.com/nuitsjp/DocumentationStrategy

theme:
  name: material
  language: ja

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.highlight
  - toc:
      permalink: true

plugins:
  - search
  - mermaid-to-image:
      # 環境変数ENABLE_PDF_EXPORTが設定されている場合のみプラグインを有効化
      # enabled_if_env: ENABLE_PDF_EXPORT
      # PDF生成時の互換性のためHTMLラベルを無効化
      mermaid_config:
        htmlLabels: false
        flowchart:
          htmlLabels: false
        class:
          htmlLabels: false
  - to-pdf:
      # enabled_if_env: ENABLE_PDF_EXPORT
      cover_subtitle: 'ドキュメンテーション戦略'
      toc_title: 目次
      toc_level: 3
      output_path: pdf/ドキュメンテーション戦略.pdf
