site_name: ドキュメンテーション戦略
site_description: 業務システムドキュメントのベストプラクティスとMermaid図表のサンプル集
site_author: Documentation Team
copyright: Copyright &copy; 2024 @nuits.jp

theme:
  name: material
  language: ja

extra_css:
  - stylesheets/pdf-fixes.css

extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.highlight
  - toc:
      permalink: true

plugins:
  - search
  - mermaid-to-image:
      # PDF生成時の互換性のためHTMLラベルを無効化
      mermaid_config:
        htmlLabels: false
        flowchart:
          htmlLabels: false
        class:
          htmlLabels: false
  - svg-to-png:
  - to-pdf:
      cover_subtitle: 'ドキュメンテーション戦略'
      toc_title: 目次
      toc_level: 3
      output_path: pdf/ドキュメンテーション戦略.pdf
